### PR TITLE
Fix dependency collection for mixed workspaces

### LINKED ISSUE #62: No support for git dependencies?
Trying to check [this](https://github.com/RazrFalcon/resvg/tree/d0bfbacef7212efce4421ec532b0d98d91820bf9) resvg commit:

```
...

    Checking resvg v0.7.0 (../Projects/rust/resvg)
    Finished dev [unoptimized + debuginfo] target(s) in 18.21s
    Scanning...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "couldn\'t find sourcefor `pico-args v0.1.0 (https://github.com/RazrFalcon/pico-args?rev=f9e8b51#f9e8b51e)`" }

failed to download `pico-args v0.1.0 (https://github.com/RazrFalcon/pico-args?rev=f9e8b51#f9e8b51e)`', src/libcoreresult.rs:997:5
```

### PR DESCRIPTION
**Pull request by jakubadamw**
Fixes #62.

`cargo geiger` has not worked well in workspaces that have a top-level
package and at least one member package. It would invoke a `cargo check`
only on the top-level package, but attempt a source analysis on the
dependencies of all packages the workspace contained, which would fail
due to the search step not being able to retrieve sources of the
dependencies that have not been `cargo check`ed.

This change fixes the problem, although it leaves open the question of how
multi-package workspaces (especially those with a top-level package,
i.e. with a non-virtual manifest) should be handled by the tool.

### CODE REVIEW

**Comment by jakubadamw** [comment]
I'll see if I can add a test for this tomorrow.

**Comment by anderejd** [comment]
Thank you! 🥇  I'll look at this and merge it soonish, perhaps later today or tomorrow evening.

**Comment by jakubadamw** [comment]
@anderejd, great! :) I've just pushed the latest changes. Many, many more tests could be written but I didn't want to invest too much time before you decide if you're happy with this flavour of UI tests.

**Comment by jakubadamw** [comment]
Okay, I see that we cannot have cross-platform tests unless we clean up the consistent emoji fallback mechanism a bit. I pushed one more commit and hopefully the builds will all be green now.

@anderejd, I don't have access to a Mac, though, so if you could try to see if the emojis are still rendering fine there, that'd be great!

**Comment by anderejd** [comment]
Thank you so much, great work :)

My schedule is super busy at the moment, but I will make the time to properly review, test and merge this later today or later this week.

**Comment by jakubadamw** [comment]
@anderejd, thanks! No rush at all, take your time. 🙂

**Comment by anderejd** [comment]
What works:
 - ✅ The unit tests pass on macOS 
 - ✅ The alignment of the emoji symbols and surrounding text is correct in the Terminal app on macOS

The unexpected:
 - I get a `WARNING: Dependency file was never scanned: /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-0.6.9/lib.rs` when scanning <https://github.com/anderejd/geiger-test>

Can you take a look at why the warning appears with this PR? If you can't then I will try to find the time next weekend. Thank you again for this PR, it looks great and you took the time to do some general code cleanup as well 👍

**Comment by jakubadamw** [comment]
@anderejd, thanks for testing this out! 🙂 I'm glad you like the "clean-up".

Indeed, I had not run this by a crate with a lock file that's not up to date with the newest versions bounded by what's in `Cargo.toml`. I now fixed this and added your test crate to the new test suite. 🙂 

I also made the progress bar actually show the real work advancement being made.

image

**Comment by anderejd** [comment]
Excellent!

**Comment by anderejd** [comment]
Released in 0.7.3.

**Pull request merged**
